### ISSUE TITLE
Use of non-breaking spaces in TLE lines generates error code 2

### ISSUE THREAD

**Issue by ptgrogan** [brandon-rhodes/python-sgp4#116]
Ran into an interesting problem today -- originally via Skyfield but posting the issue here closer to the source.

I had a user supply a TLE that incidentally had some non-breaking space (ASCII 160) characters replacing some regular space (ASCII 32) characters. The non-breaking spaces must have been copied from a web-based source that substituted non-breaking spaces to make it display better on the page.

When used as input to SGP4 propagation (with acceleration), the malformed TLE generates an error code 2 suggesting the mean motion falls below zero. Inspecting the dump shows that many attributes have been zeroed out, yet no error appears to warn of an invalid TLE until propagation is attempted. The misleading error code 2 obfuscates the source problem.

The native Python code (sgp4.model) correctly identifies a validation issue.

Minimal example with caveats that non-breaking spaces might not be rendered correctly from the Markdown source:
```
from sgp4.api import Satrec

# with non-breaking space (replaces all characters that could be non-empty according to the spec but are empty in this case)
line1 = '1 43737U 18096U   23104.23131873  .00314780  00000+0  18505-2 0  9999'
line2 = '2 43737  97.3248 199.0316 0005801 347.9317  12.1809 15.77351267244832'

# without non-breaking space
# line1 = '1 43737U 18096U   23104.23131873  .00314780  00000+0  18505-2 0  9999'
# line2 = '2 43737  97.3248 199.0316 0005801 347.9317  12.1809 15.77351267244832'

satellite = Satrec.twoline2rv(line1, line2) # no error here with non-breaking space and accelerated C code

from sgp4.conveniences import dump_satrec
for x in dump_satrec(satellite):
  print(x) # many attributes zeroed out with non-breaking space and accelerated C code

jd, fr = 2460053, 0.0
e, r, v = satellite.sgp4(jd, fr)
print(e, r, v) # error code 2 with non-breaking space and accelerated C code
```
I understand that this is an issue with the original Vallado C code and there may not be an easy way to patch; however, it might be worth adding a check to handle non-breaking spaces in a more elegant way (if possible) as it is a tricky issue to debug.

**Comment by brandon-rhodes** [comment]
Happily, the non-breaking spaces came through correctly (I used the little GitHub "copy" button in the corner of the text area), so I had no problem running your script!

For compatibility and speed, I don't want `sgp4` to perform extra checks that the accelerated C++ code doesn't, but I'm happy to add a bit more logic to the slow fallback Python code that runs on systems where the C++ doesn't compile. I've just landed a change so that a check is made for non-ASCII strings, and I've added documentation to show users how to call the fallback code, like this:

```
>>> from sgp4.earth_gravity import wgs72
>>> from sgp4.io import twoline2rv
>>> assert twoline2rv(s, t, wgs72)
```

To install the development version and try this out, run:
```
pip install -U https://github.com/brandon-rhodes/python-sgp4/archive/master.zip
```
(Though of course that might break your C++ acceleration, if you don't have a compiler handy, so after trying out the new code you might want to uninstall and re-install the official version until the next release adds the new checking code permanently.)

Thanks for letting me know about this edge case; hopefully it hasn't tripped anyone else up!
