### ISSUE TITLE
Return state for decayed satellites?

### ISSUE THREAD

**Issue by anyeli** [brandon-rhodes/python-sgp4#20]
In your implementation of sgp4, in propagation.py, you have the following "fix":

     #  sgp4fix for decaying satellites
     if mrt < 1.0:

         satrec.error_message = ('mrt {0:f} is less than 1.0 indicating'
                                 ' the satellite has decayed'.format(mrt))
         satrec.error = 6;
         return false, false;

Returning (false,false) discards the calculated values, a behavior I find to be rather unhelpful - although the state is invalid, it is still useful, e.g. for solving for impact time and location via Newton's method.  Could you return the calculated values instead?  You are already indicating the error condition via error and error_message.

**Comment by brandon-rhodes** [comment]
That's an interesting question. In the C language SGP4 code that this Python implementation is based on, the result is returned as:
https://celestrak.com/publications/AIAA/2006-6753/AIAA-2006-6753-Rev2.pdf
```
 if (mrt < 1.0)
 {
// printf("# decay condition %11.6f \n",mrt);
 satrec.error = 6;
 return false;
 } 
```
The problem with returning anything other than `false` is that normal users would think that the satellite were still flying, and would expect it to be at exactly the returned coordinates, because in those cases where the algorithm does not return `false`, users think that they can use the position as a real position for the satellite.

Can you adjust your algorithm so that it searches for the moment when the satellite transitions from a valid SGP4 position to the moment where this routine returns `false`, and compute your re-entry from there? If you wait until a moment when this returns `false`, then I think you are already past the point where SGP4 can return good positions, and you will be running Newton's method on an invalid starting point.

**Comment by anyeli** [comment]
The Celestrak implementation of SGP4 returns false, but it still returns the values through array arguments.  This seems intentional to me; otherwise they could have done this check immediately after calculating mrt and avoided calculating the Cartesian state in the first place.

Newton's method works fine inside the Earth.  The function doesn't become discontinuous at the surface of the Earth.  Of course I can write hacks and brute force methods to work around a programming interface that loses information, but I don't because it's silly - I can just delete one line of code in my copy of an open source library, and I don't even need to recompile anything.  I would imagine anyone else doing serious work would be tempted to do the same.

But I want to be cooperative.  Perhaps you could add an optional "advanced" switch, either stored in the Satellite object or passed as an optional argument to propagate and sgp4 for users who don't want to lose the value inside the Earth and actually check the error code and/or perform their own checks?

**Comment by brandon-rhodes** [comment]
When I get a chance to return to the code in a few weeks, I'll look at the possibility, as I tackle the larger question of making the code as friendly as possible to Numba optimization — letting the caller pass in `r` and `v` vectors, for example, might allow things to be kept efficient while still letting the vector results be always examined.

But if the extra complexity in that case carries any cost, I'll have to weigh it against the fact that the SGP4 result loses physical significance long before the vector reaches the Earth's surface — once the satellite comes into contact with the upper atmosphere, the SGP4 numbers rapidly lose any meaning. When satellites come down, scientists are never able to predict an impact point, but instead have to provide a guess that is often a swath hundreds or thousands of miles long. The dynamics of how pieces slow in the upper atmosphere, transition to tumbling, and then fall towards the surface is not modeled by SGP4 — and indeed are not currently predictable by any method, I don't think?

**Comment by anyeli** [comment]
Fair enough, precisely solving for "impact" with SGP4 is largely an academic matter - indeed, most satellites disintegrate well before reaching the surface.  Nonetheless, it's still useful to have a propagator that behaves like a smooth mathematical function near the suborbital-orbital boundary, so that you can still do orbit determination reliably and at least produce low fidelity predictions - which is much better than none at all.

**Comment by brandon-rhodes** [comment]
Good news: I have decided that the satellite `.error` should be the official way to see if the computation worked or not, instead of insisting on `nan` in the returned vectors in every error case. So I have updated the code to return the computed vectors in the case you cite: where the satellite is below sea level. The improvement should appear in the next release of this library, which hopefully will be by the end of the year!
