### ISSUE TITLE
Consider accepting timezone-aware datetimes in calls to propagate

### ISSUE THREAD

**Issue by Carl4** [brandon-rhodes/python-sgp4#22]
The fix would be pretty minimal, and it would be convenient, but I wasn't sure if there was a reason not to.

``` python
if isinstance(year, datetime):
    year, month, day, hour, minute, second  = year.timetuple([:6]) 
    second += year.microsecond / 1.0e6
```

This would go [here](https://github.com/brandon-rhodes/python-sgp4/blob/aab2dbb4daa6f24aa60626ce971711964d53c5fa/sgp4/model.py#L46) in the model propagate function. month, day, hour, minute, second would all be optional with defaults.

**Comment by brandon-rhodes** [comment]
The main reason, I suppose, is that I intended `sgp4` as a low-level library that other projects (like my own Skyfield library, that does take datetimes) would build on, and since the original C code doesn't take alternative forms of time, I wanted to keep the Python sgp4 simple as well.

If we did add such logic here, I'd want to probably name it `propagate_datetime()`, so that the main routine wouldn't involve the complexity of an `isinstance()`.

It's possible that I should jump into the sgp4 docs this week and add a prominent mention of Skyfield, so that users know where to find higher-level date and time routines — do you think that might help? I'm only now realizing that merely because I use sgp4 through Skyfield doesn't mean that any other developers even know that Skyfield exists!

**Comment by Carl4** [comment]
I wasn't aware of Skyfield. I'll check it out in a bit.  I'm mostly using your sgp4 library so I don't have to deal with linking in C code to do the math.  Thought I'm just realizing that I'm going to need a reliable ECI to Geodetic conversion very soon too.  I'll take a look at Skyfield.

**Comment by brandon-rhodes** [comment]
Looking back at this: I’m not sure how this would work with “timezone-aware datetimes” — doesn’t `timetuple()` ignore time zone information and simply return the raw hours, minutes, and seconds? So that if the date were in a non-Greenwich timezone, sgp4 would give the wrong answer because it would interpret the date as UT?

**Comment by brandon-rhodes** [comment]
1. Pending further information about whether `timetuple()` would handle time zone conversions the way SGP4 needs them handled, I am going to close this issue for now.
2. If we ever re-open the issue, I will probably only want tweaks to documentation to result from this issue. That is, I'm fine with someone writing a bit more for the docs that show how to bring together `tz` and Python to turn a datetime into something usable for a `Satrec`. But I want this library to remain a very thin — a minimally thin, in fact — wrapper around raw SGP4, so that it imposes no additional weight on projects that need that library alone.

Thanks for the idea, and I'm not opposed to an update to the docs someday! Feel free to re-open if anyone wants to suggest some text.
