### ISSUE TITLE
Semi-major axis

### ISSUE THREAD

**Issue by AlexJohnson1995** [brandon-rhodes/python-sgp4#34]
How can I get a semi-major axis of the satellite? I have found a wrapper method called "initl" on "propagation.py", but did not understand how to use it in order to get the ao. Could you, please, give an example?

**Comment by ckuethe** [comment]
```
tle = [
  'ISS (ZARYA)',
  '1 25544U 98067A   19203.55917916  .00000561  00000-0  17341-4 0  9990',
  '2 25544  51.6424 185.7766 0006739 167.1766 299.1181 15.50994811180747',
]

iss = sgp4.io.twoline2rv(tle[1], tle[2], sgp4.earth_gravity.wgs84)
a = (iss.whichconst.mu / (iss.no/60.)**2)**(1./3.)
print a
```

prints `6792.46118364`

`iss` is, of course, a `sgp4.model.Satellite`. According to the docs, `Satellite.no` is the satellites mean motion in radians per minute.  Left as an exercise to the reader is the conversion of mean motion to orbits per day, or whatever other units you want to use for computing semi-major axis.

`mu` is the standard gravitational parameter whose value varies slightly with each particular reference system. In my example, I'm using WGS84, and conveniently a `Satelllite` knows which gravity model it was passed (`whichconst`), and the gravity model includes the value of `mu` defined in that reference system.

Have a quick look at [wikipedia](https://en.wikipedia.org/wiki/Mean_motion) and [space stackexchange](https://space.stackexchange.com/questions/18289/how-to-get-semi-major-axis-from-tle) to really understand what's going on, rather than just believing my handwaving.

**Comment by AlexJohnson1995** [comment]
It worked, thanks a lot! I transfered the result into units required by me (radians per seconds), then used formula to get `a`
