### ISSUE TITLE
Brouwer vs. Kozai mean motion

### ISSUE THREAD

**Issue by bamablee** [brandon-rhodes/python-sgp4#43]
I have an application for which I need to be able to produce TLE's from the mean elements in the "model" member of a Skyfield EarthSatellite object. After implementing the text-rendering function, I tried round-tripping a TLE through it and noted that the code didn't reproduce the mean-motion term correctly.  

Tracing through twoline2rv() eventually led to the section of the `sgp4.propagation._initl()` function that "un-Kozai's" the mean motion, which explained the difference.  I tried copying the calculation of the "del_" scale factor into my routine to "undo" the Kozai --> Brouwer transformation, but unfortunately it's a non-conservative transform b/c the first intermediate variable in the `del_` calculation ("ak") depends on the input mean-motion value.

Would it be possible to add a utility function to perform the inverse (Brouwer --> Kozai) transformation on mean motion?

**Comment by brandon-rhodes** [comment]
I would be happy for the library to gain such a function, and would accept a pull request that added one. Could you supply code with an example satellite, the mean motion number you're getting out, and the un-Kozai's number you would like the future routine to produce instead? Thanks!

**Comment by brandon-rhodes** [comment]
@bamablee — There is now an import and export routine available in the library itself, and, happily, it looks from `sgp4/tests.py` like it successfully round-trips the mean motion; I see the input mean motion `10.84869164` for Vanguard 1 come out as the same value in its output TLE.

I am going to hope for the moment that this means your problem is solved, and close this issue; but please comment further if the new export routines do not print exactly the values you need. Thanks!
