### ISSUE TITLE
numba makes sgp4 slower

### ISSUE THREAD

**Issue by Juanlu001** [brandon-rhodes/python-sgp4#46]
I still didn't have time to craft a proper reproducible example, but we observed a noticeable slowdown when using sgp4 2.2, which is entirely consistent with [this observation by @rirze](https://github.com/brandon-rhodes/python-sgp4/pull/36#issue-304108165):

> In my course of using this library, I have found Numba to be increasing my runtimes for the sgp4 routine, rather than decreasing it. [...] In fact, on my machine, Numba compilation increases sgp4 runtime by 2-3x! (Ubuntu 18.04 Windows Subsystem Linux, Python 3.6.4)

We are also observing a large number of warnings:

```
tests/test_full_pipeline.py::test_orbit_assigners_are_recovered
  /home/juanlu/.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py:1698: NumbaWarning: 
  Compilation is falling back to object mode WITH looplifting enabled because Function "sgp4" failed type inference due to: Untyped global name '_dpper': cannot determine Numba type of <class 'function'>
  
  File "../../../../.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py", line 1838:
  def sgp4(satrec, tsince, whichconst=None):
      <source elided>
  
           ep, xincp, nodep, argpp, mp = _dpper(
           ^
  
    @jit(cache=True)

tests/test_full_pipeline.py::test_orbit_assigners_are_recovered
  /home/juanlu/.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py:1698: NumbaWarning: 
  Compilation is falling back to object mode WITHOUT looplifting enabled because Function "sgp4" failed type inference due to: Untyped global name '_dpper': cannot determine Numba type of <class 'function'>
  
  File "../../../../.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py", line 1838:
  def sgp4(satrec, tsince, whichconst=None):
      <source elided>
  
           ep, xincp, nodep, argpp, mp = _dpper(
           ^
  
    @jit(cache=True)

tests/test_full_pipeline.py::test_orbit_assigners_are_recovered
  /home/juanlu/.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "sgp4" was compiled in object mode without forceobj=True, but has lifted loops.
  
  File "../../../../.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py", line 1700:
  #@jit
  def sgp4(satrec, tsince, whichconst=None):
  ^
  
    state.func_ir.loc))

tests/test_full_pipeline.py::test_orbit_assigners_are_recovered
  /home/juanlu/.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/numba/object_mode_passes.py:187: NumbaDeprecationWarning: 
  Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.
  
  For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
  
  File "../../../../.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py", line 1700:
  #@jit
  def sgp4(satrec, tsince, whichconst=None):
  ^
  
    warnings.warn(errors.NumbaDeprecationWarning(msg, state.func_ir.loc))

tests/test_full_pipeline.py::test_orbit_assigners_are_recovered
  /home/juanlu/.pyenv/versions/3.7.4/envs/mbp37_4/lib/python3.7/site-packages/sgp4/propagation.py:1698: NumbaWarning: Cannot cache compiled function "sgp4" as it uses lifted loops
    @jit(cache=True)

```

sgp4 own tests do take much longer now, but this is somewhat to be expected because the compilation step takes some time:

```
$ time python -m sgp4.tests 2> /dev/null 

real	0m12,655s
user	0m12,631s
sys	0m0,537s
$ export NUMBA_DISABLE_JIT=1
$ time python -m sgp4.tests
...............
----------------------------------------------------------------------
Ran 15 tests in 0.080s

OK

real	0m0,678s
user	0m0,724s
sys	0m0,228s
```

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I will go in and remove the Numba experiment, since its results were not a consistent improvement for users.

In the meantime, if you will switch to the new API described on the project’s PyPI front page, you should get vastly accelerated C++ code (in most cases). If there are any blockers in front of your trying out the `Satrec` object, please let me know and I'll see if I can remedy them:

https://pypi.org/project/sgp4/

I'll keep this issue open until I've released a new version that is Numba-free. I had forgotten that the older versions did not include the Numba experiment, and that this would be the first time folks would run into it. (Since I myself never have Numba installed, I did not, alas, see its effects locally.)

**Comment by brandon-rhodes** [comment]
@Juanlu001 — There! I have removed it. Could you try:

    pip install https://github.com/brandon-rhodes/python-sgp4/archive/master.zip

and let me know whether the problem clears up? If so then I will release a new version immediately.

**Comment by Juanlu001** [comment]
@brandon-rhodes sure! on it right now

**Comment by Juanlu001** [comment]
@brandon-rhodes confirmed that with current `master` the runtime is equal to having `export NUMBA_DISABLE_JIT=1`.

**Comment by brandon-rhodes** [comment]
I have just released 2.3 with the Numba experiment removed. A normal `pip` install should now give you a correctly functioning version. Let me know if you notice any regression.

**Comment by stuartarchibald** [comment]
It seems like `@jit` was used in the above which permitted fall back to "object mode" compilation (see [here](https://numba.readthedocs.io/en/stable/user/5minguide.html#what-is-nopython-mode) for what this means). The warning messages like:
```
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "sgp4" failed type inference due to: Untyped global name '_dpper': cannot determine Numba type of <class 'function'>
```
suggest that `_dpper` was not decorated with `@jit` which may have permitted Numba to compile the function in `nopython` mode. The result of this is that Numba generates compiled code that uses the Python API to do the work instead of being able to generate native code, as a result, not necessarily any faster than pure python.

**Comment by astrojuanlu** [comment]
Unfortunately `@jitting `_dpper` is not enough, because all these functions receive a `sgp4.model.Satrec` that numba doesn't understand. I am making some experiments with `@jitclass` but can't promise anything.

**Comment by astrojuanlu** [comment]
...I can promise something :) #76
