### ISSUE TITLE
sgp4() should take tsince() as an argument

### ISSUE THREAD

**Issue by interplanetarychris** [brandon-rhodes/python-sgp4#52]
In the 2.0 extension, sgp4 has been modified (perhaps too conveniently) to take arguments of a different from from the previous python version, and the SGP4.CPP function itself.

https://github.com/brandon-rhodes/python-sgp4/blob/2e1a06ff41122ba7d4ee6a3412788cd82455165b/extension/wrapper.cpp#L126-L127

This could be preserved as an "sgp4_jd()" convenience function.

I have an incoming PR which reverts this.

Additionally, the proliferation of the jd, fr separation for julian dates perhaps creates more problems than it solves.  Opening a separate Issue to discuss that.

**Comment by interplanetarychris** [comment]
The same perhaps applies to `Satrec__sgp() -> _vectorized_sgp4`, although, as it is not a legacy function, the distinction is less important.

**Comment by brandon-rhodes** [comment]
We, alas, cannot change the definition of `Satrec.sgp4()` without breaking existing software that has migrated to it. What if we made the rule that when given one float, `sgp4()` interprets it as a `tsince`, but when given two floats, `sgp4()` interprets them as a `jd` and `fr`?

Though that’s probably poor design because then the first argument would mean different things though it would always have to carry one name.

I was unaware of Python code that used `tsince` internally and would use a raw function if I provided one. If two separate functions are indeed the cleanest approach, then `sgp4_raw()` or `sgp4_tsince()` might be reasonable names.

**Comment by brandon-rhodes** [comment]
Oh!

I should explain my choice here, in case it influences your desire to add another function.

My design was intended to make the vectorized and non-vectorized versions of the main compute call as symmetric as possible. If all I had been doing was writing the `sgp4()` call for `Satrec`, I would have specified its argument as `tsince` and left it at that.

But the `sgp4()` method of a `SatrecArray` could not reasonably take a `tsince`, I didn't think, because a `tsince()` like `100.0` would mean something different for every satellite in the array: it would mean “100 minutes past this satellite’s epoch” where every satellite could have a different epoch. I therefore could think of no possible use for a satellite array routine that took the value `tsince`. The only reason I could think of for asking an array of satellites to compute their positions was to get their positions at a single calendar date and time that is the same for every satellite.

Therefore, `SatrecArray.sgp4()` needed to take a Julian date, and I wrote it to do so.

Therefore — and here you might disagree — `Satrec.sgp4()` also needed to take a Julian date, for symmetry. I was not interested in supporting a library where two methods with the same name (but I suppose I could have renamed the `SatrecArray` method?) took different numbers of arguments that meant different things.

**Comment by interplanetarychris** [comment]
Its not good for backwards compatibility.  Someone upgrading to python-sgp4.v2 needs to change all their sgp4() functions to pass jd, jr instead of tsince.

I'd recommend fixing the "existing software" to use a renamed-Satrec() method, as the old user base is probably larger than the "existing software" based on v2.

In the mean time, I checked in https://github.com/brandon-rhodes/python-sgp4/pull/49/commits/58c7ff97206c6817541011238a5d2192f2233bfe and https://github.com/brandon-rhodes/python-sgp4/pull/49/commits/85b5c828e7a8039ebf8b8bdff623703c7b2dd576 which adds the sgp4(tsince) method to wrapper.cpp, and associated new unit tests.

**Comment by brandon-rhodes** [comment]
> Its not good for backwards compatibility. Someone upgrading to python-sgp4.v2 needs to change all their sgp4() functions to pass jd, jr instead of tsince.

First, I should double-check something: I tried to prevent any difficultly on upgrade, and wrote tests that I thought protected against any change in behavior. As long as existing code continues to use the class name `Satellite` that they used previously, their `tsince` argument will continue to have its old meaning, I think?

Second: I'll be happy to add a small "Porting to v2" guide to the docs, explaining the options of (1) leaving legacy code unmodified, (2) switching to `Satrec` and `sgp4_tsince()` but having no quick way to switch in the future to a `SatrecArray` if an app uses `tsince` values internally, and (3) switching to `Satrec` `sgp4()` which requires switching to a Julian Date but then leaves apps ready for the fast `SatrecArray`.

**Comment by interplanetarychris** [comment]
OK - I guess I'll concede on this, on the basis that with arrays, the absolute time does make more sense. Given that I've added the function in my PR, I've got what I need.
