### ISSUE TITLE
jdsatepoch = jd + fr.   Why?

### ISSUE THREAD

**Issue by interplanetarychris** [brandon-rhodes/python-sgp4#53]
In the v2.0 updates, the epoch has been split to its integer and fractional components, apparently in an effort to maintain compatibility with the SGP.CPP code.  However, that code also doesn't consistently use it -- and the separation of the pieces have no apparent benefit (to me at least).

Is there a reason that the user must be made to manage these variables in their day and day-fraction components?

**Comment by brandon-rhodes** [comment]
I'll update the docs to address this question!

**Comment by brandon-rhodes** [comment]
All right, I have tried writing up a first draft of explaining how astronomers express dates using two floats. Let me know how it could be clarified to make it clear to users how the standard practice works that, apparently, the underlying SGP4 has decided to follow.

**Comment by interplanetarychris** [comment]
Thanks for the explanation - however, I don't believe it is true that SGP4 makes use of the fractional precision in anywhere that is used for calculations -- only the jday and invjday routines use the fraction, and probably because the code was borrowed from an astronomer ;-)

`sgp4init()` takes `C-double epoch`  days since jan 0, 1950. 0 hr
`sgp4()` takes `C-double tsince`   elapsed minutes since the above epoch

Both should allow for sub-microsecond precision using a C-double, for their intended use -- tsince shouldn't grow large enough need more precision than the propagator provides for...

**Comment by brandon-rhodes** [comment]
Yes, the `tsince` value, by being centered on a present date, is able to blissfully use all its digits to provide tiny fractions of a second near its epoch. But converting a Julian date to a `tsince` would involve a loss of precision, which I am assuming is why Vallado's most recent code adds a `jdsatepochF` value in addition to what I think was traditionally just a `jdsatepoch` value. This lets him write an expression for `tsince` that carries as much of the precision of the date fraction through to the final value as possible:

https://github.com/brandon-rhodes/python-sgp4/blob/2a365a3bc8b2e2343a4efe3d611b89c971676870/extension/SGP4.cpp#L2356

Note the subtractions, which turn both floats into small-as-possible numbers before adding and throwing away the extra digits of the fractional part — that’s the standard math maneuver I’ve run into elsewhere when astronomers try to support small fractional days.

I am having to use the code as evidence of intention here because I see no mention of the change either in the full source code:

https://github.com/rirze/sgp4-cpp

nor in the notes accompanying the "Revisiting" paper:

https://celestrak.com/publications/AIAA/2006-6753/

nor in any of the errata to his book:

https://celestrak.com/software/vallado-sw.php

The value `jdsatepochF` also appears in the FORTRAN version, which I take as evidence that it is not a quirk introduced casually into the C++ code, but is instead the way the library is intended to work from now on.

**Comment by interplanetarychris** [comment]
OK - Thanks for the detailed explanation and documentation update. It makes me appreciate the paragraph in `functions.jday()` more than I did on the first read.  I can appreciate why the separate variables are introduced where they are currently used in Vallado's code.  

Still, I think Issue https://github.com/brandon-rhodes/python-sgp4/issues/52 should create a "pure" version of `sgp4(tsince)` that works exactly like the CPP function it is calling, and I will submit a PR for a version which introduces that, and renames the current wrapper function to `sgp4_jd(jd,fr)` for convenience.
