### ISSUE TITLE
Units of Bstar coefficient

### ISSUE THREAD

**Issue by Darkissuez** [brandon-rhodes/python-sgp4#60]
Hello, 
I have a doubt about your documentation concerning the Bstar term. Your comments say that it is in units kg / (m2 ER). But the TLE documentation says it is in ER^-1 units. 
The definition of Bstar is Bstar = rho_0 * CD * A / (2 * m), if I am not wrong

I went to the function twoline2rv() and it seems that there is no conversion made. I hope you can enlighten me

Thank you

**Comment by brandon-rhodes** [comment]
Which TLE documentation suggests those units — I see something similar at spaceflight.nasa.gov but it will be helpful to read exactly the same docs you are.

Here is the parameter description from which the documentation takes the description. Since ideally this Python library is simply a thin wrapper around this C++ code, I mostly just copied the descriptions across to the Python and docs:

https://github.com/brandon-rhodes/python-sgp4/blob/72b1f480548a9effdf0f51aa5fe149cea39083e7/extension/SGP4.cpp#L1288

It's quite possible that I misunderstood the C++ code author's intentions there, but I took "kg" to indicate mass in the numerator. Mass is also mentioned in the cryptic definition of bstar at:

https://www.celestrak.com/publications/AIAA/2006-6753/AIAA-2006-6753.pdf

— but I don’t see that it gives units for it explicitly.

**Comment by Darkissuez** [comment]
Indeed the original code says that the units for Bstar are [kg/m^2 ER]. But maybe it is a bug, because everywhere else it is stated that the units are [ER^-1], namely https://www.celestrak.com/columns/v04n03/ , https://spaceflight.nasa.gov/realdata/sightings/SSapplications/Post/JavaSSOP/SSOP_Help/tle_def.html , https://ai-solutions.com/_help_Files/spacecraft_bstar_nanosecond.htm and even Vallado's book [Fundamentals of astrodynamics and applications - chapter 2.4.2]. And it is also easy to check that the units are actually  [ER^-1]  by doing a dimension analysis to the formula Bstar = rho_0 * CD * A / (2 * m), given that rho is expressed in [kg / (m2 * ER)]

However, Vallado states that Bstar is usually transformed to B (or BC) which he calls the ballistic coefficient:   B = R_E * rho / (2Bstar) (I saw this in the document you provided). and the units of B are indeed [kg/m^2 ER]. So maybe the two coefficients got mixed up.

Nevertheless, the SGP4 equations use B*, not B, thus I think that the misunderstanding is just in the comments, not in the code itself

**Comment by brandon-rhodes** [comment]
Thanks for the link to the “Frequently Asked Questions” — I had not thought to look there for the units, and it provides exactly the explanation I was missing. I think your theory is exactly correct about how the comments in the Vallado code could have wound up wrong. Now that we have a plausable story behind why this library should (gulp!) dissent from the C++ library it wraps, I'll go try making the change.
