### ISSUE TITLE
export_tle roundtrip issues

### ISSUE THREAD

**Issue by astrojuanlu** [brandon-rhodes/python-sgp4#71]
While studying #70, I discovered a roundtrip problem with `export_tle`:

```
>>> lines = """1 46272U 20061A   20311.82207422  .00000083  00000-0  68546-5 0  9999
... 2 46272  97.3995  23.7575 0006827 352.5560   7.5569 15.20743438  9810"""
>>> print(lines)
1 46272U 20061A   20311.82207422  .00000083  00000-0  68546-5 0  9999
2 46272  97.3995  23.7575 0006827 352.5560   7.5569 15.20743438  9810
>>> sat = twoline2rv(*lines.splitlines(), wgs84)
>>> print("\n".join(export_tle(sat)))
1 46272U 20061A   2020311.82207422  .00000083  00000-0  68546-5 0  9993
2 46272  97.3995  23.7575 0006827 352.5560   7.5569 15.20743438  9810
```

And I think it also happens with other examples in https://github.com/brandon-rhodes/python-sgp4/blob/master/sgp4/SGP4-VER.TLE.

**Comment by brandon-rhodes** [comment]
Is it failing to truncate the year to 2 digits? We should go look at whether I always keep `epochyr` to 2 digits; there is an underlying Python object, if the C++ code doesn't compile, that I think might use a 4-digit year because I thought I was being clever and "fixing" a shortcoming of the underlying code. (This was long ago, before I decided to wrap the real C++ code, when I didn't know that I would wish I had stayed 100% compatible with it!)

If you have time to dig in, let me know what you find; otherwise I'll try to take a look within the next few weeks.

**Comment by astrojuanlu** [comment]
Interestingly, this only seems to happen with the legacy `sgp4.io.twoline2rv`. Using `Satrec.twoline2rv` and then `export_tle` gives the expected result:

```
>>> lines = """1 26975U 78066F   06174.85818871  .00000620  00000-0  10000-3 0  6809
... 2 26975  68.4714 236.1303 5602877 123.7484 302.5767  2.05657553 67521"""
>>> print(lines)
1 26975U 78066F   06174.85818871  .00000620  00000-0  10000-3 0  6809
2 26975  68.4714 236.1303 5602877 123.7484 302.5767  2.05657553 67521
>>> sat2 = Satrec.twoline2rv(*lines.splitlines(), WGS84)
>>> print("\n".join(export_tle(sat2)))
1 26975U 78066F   06174.85818871  .00000620  00000-0  10000-3 0  6809
2 26975  68.4714 236.1303 5602877 123.7484 302.5767  2.05657553 67521
```

and probably it has to do with this:

https://github.com/brandon-rhodes/python-sgp4/blob/03169013eea2ddcedab5d2b74d582905025368bf/sgp4/model.py#L66-L67

Do you prefer to close this issue as "won't fix", or should we attempt to get it right somehow?

**Comment by brandon-rhodes** [comment]
Ah, you found it ­— yes, the `self.epochyr %= 100` line fixes the pure-Python satellite object’s 4-digit year so that it goes back to behaving like a proper SGP4 2-digit year. So when the old Python version is used as a fallback by the modern code, its quirk is corrected.

But since the old version is still in the code, I don’t see any way to prevent users from trying to build old satellites and passing them to `export_tle()`, and the fix is so simple and computationally inexpensive that I see no reason not to do it. Would you like to submit a PR that does a `% 100` in `export_tle()` on the year, so that it always comes out looking correct?

**Comment by astrojuanlu** [comment]
> Would you like to submit a PR that does a % 100 in export_tle() on the year, so that it always comes out looking correct?

Absolutely!
