### ISSUE TITLE
A TLE satellite number that starts with spaces gets parsed wrong

### ISSUE THREAD

**Issue by pysda** [brandon-rhodes/python-sgp4#90]
Hello, I've discovered some usefulness for my work in the Satrec object for parsing tles and the new (2020) added export_tle() method. While performing some tests ingesting a space-track tle, and subsequently writing the same tle sets using the export_tle call I'm noticing some errors, specifically on satnums < 10000. It appears something between columns 8&9 are not parsed to the output correctly. Thanks very much for the great code I wanted to bring this to your attention. 

I've attached the input tle file, test code, and output exported txt file.
[export_tle.zip](https://github.com/brandon-rhodes/python-sgp4/files/6079068/export_tle.zip)

**Comment by brandon-rhodes** [comment]
Alas, the output I get is different, which might make this more difficult to debug:
```
1 00011U 59001A   20003.82564200  .00000280  00000-0  15331-3 0  9995
2 00011  32.8687 317.2608 1467951  36.4758 332.7376 11.85648920597063
1 00020U 59007A   20003.80103211 -.00000068  00000-0 -22703-4 0  9998
2 00020  33.3452  52.1727 1666929 108.0271 270.8469 11.55689532211472
1 00045U 60007A   20002.02051212 -.00000058  00000-0  12258-4 0  9995
2 00045  66.6953 102.1385 0248291  77.1271 285.7439 14.33661712 98703
1 00226U 62002A   20005.89260196 -.00000130  00000-0  11566-4 0  9996
2 00226  48.2949 211.0742 0078489 284.2692  74.9500 14.45664339 27700
1 01272U 65016H   20002.91350731 -.00000044  00000-0  63638-5 0  9993
2 01272  70.0779 215.7476 0023669 327.8755  32.0907 13.94214062787835
1 03266U 68042A   20001.87009191 -.00000019  00000-0  12547-4 0  9999
2 03266  98.8103 227.2453 0052318 215.0190 144.7539 14.15271044579913
1 05174U 71035A   20003.69751980 -.00000006  00000-0  73180-5 0  9994
2 05174  74.0450  97.6025 0017705 138.9894 221.2593 14.33275655542893
1 09903U 77024A   20005.80766062  .00000180  00000-0  97279-4 0  9990
2 09903  81.2580 257.9214 0036827 172.3273 187.8468 14.08289775196344
1 10010U 77036A   20001.61674958 -.00000054  00000-0  41706-5 0  9997
2 10010  65.8650  53.2967 0713143 253.9826  98.1536 12.30336768914993
1 10288U 77079D   20002.76763056 -.00000003  00000-0  92204-4 0  9998
2 10288  74.0231 151.4879 0044287  41.0594  67.1723 12.42220462921037
```
What versions of Python and sgp4 are you using, and what operating system?

**Comment by pysda** [comment]
Interesting! I'm on Windows 10
Python 3.8.5,  sgp4 2.17

**Comment by brandon-rhodes** [comment]
Let's compare the input line and the output line you're getting for Line 1:
```
1    11U 59001A   20003.82564200  .00000280  00000-0  15331-3 0  9995  # INPUT
1 000115 9001A    20003.82564200  .00000280  00000-0  15331-3 0  9995  # OUTPUT
```
It looks like the `5` that should be the initial digit of the international designator `59001A` is getting moved over and being treated like it's the classification, which should instead be `U`. Here's the code that produces that part of the output string:

https://github.com/brandon-rhodes/python-sgp4/blob/e5f0f5b7695fc53daf2cd7fb6c36ae73af528f97/sgp4/exporter.py#L28

I don't see how that code can fail to put the value of `.classification` in the right place. Could you try printing that attribute of the satellite to see whether it's `5` or `U`?

**Comment by pysda** [comment]
It appears satnum=11 classification attribute is a '5'.
tles[0]
Out[16]: 
('1    11U 59001A   20003.82564200  .00000280  00000-0  15331-3 0  9995',
 '2    11  32.8687 317.2608 1467951  36.4758 332.7376 11.85648920597063')
sat.satnum, sat.classification
Out[17]: (11, '5')

**Comment by brandon-rhodes** [comment]
So the problem is apparently not the export routine, but the import routine, because the classification should (I think?) be `U` for that satellite. If you have a moment, update the title of this issue; and, wow, I'll have to think about how we might debug the import routines, because if you're using a compiled and accelerated version of SGP4, then the problem might be in how Windows `scanf()` routines behave. This would not be the first problem this library has had with Windows `scanf()`.

**Comment by brandon-rhodes** [comment]
Oh! I see the problem.

The TLE input routine requires 5 digits in columns 3-7 of Line 1. Your satellite records, alas, have spaces there instead, so the routine that looks for the 5-digit satellite number picks up `11U ` as the satellite number, then thinks the `5` is the classifier letter.

What is your source of TLE data? If its formatting can't be fixed, then maybe you can just fix the spaces and turn them into zeros before passing the strings to `sgp4`.

It seems to me a bit unfortunate that the official SGP4 code isn’t stricter about the checks it does when importing a TLE. Maybe I should add a check to the Python wrapper for whether column 3 is whitespace or not, since I don't think a TLE can correctly parse otherwise. The danger would be breaking projects that have been parsing broken TLEs successfully to this point because they don't ever check the satellite number or classification.

Or maybe I could do something more clever. I'll take a look.

Meanwhile, let me know where you got the TLE lines from, as I'm curious whether it's a data source that might affect lots of users!

**Comment by brandon-rhodes** [comment]
(I just double-checked, and realized that I've been accidentally running your test script with my non-accelerated version of the library, which doesn't have the problem because it uses Python to do the parsing. Now that I'm using the C++ code, I see the same symptom as you do, so I've removed “Windows” from the title.)

**Comment by brandon-rhodes** [comment]
I've just landed a basic fix, though I should also check whether it can be done with just a single character operation rather than 5 per line. If you'd like, you can try out the new version with:
```
pip install -U https://github.com/brandon-rhodes/python-sgp4/archive/master.zip
```
There was, interestingly enough, already a test to make sure that a line with leading spaces in its satellite number at least parsed successfully; but the test didn't go on to confirm that the international designator and classification were read correctly, which I've fixed.

**Comment by pysda** [comment]
> What is your source of TLE data?

Hi Brandon, the source txt file I was reading in was taken from a space-track.org query. Appears that their queries _may have leading padding zeros but not on all occasions. Their TLE format description help page states 
"Object numbers less than 10000 are always aligned to the right, and padded with zeros or spaces to the left." It sounds as if the parsing may not have accepted whitespace as valid columns to build the 5-digit (column) sat number? I am attempting to install your fix above to check but I'm not sure it's going through. Thanks again.

**Comment by brandon-rhodes** [comment]
> It sounds as if the parsing may not have accepted whitespace as valid columns to build the 5-digit (column) sat number?

Correct! The Celestrak C++ version of SGP4, that this Python library wraps, uses `scanf()`, so the 5-character field doesn’t start until the first non-whitespace character. So if the satellite number isn’t zero padded, then the classification character (`U` or whatever) was getting pulled into that field too.

I'm not sure whether space-track uses Celestrak’s SGP4 implementation; they might use their own that handles the case of leading whitespace just fine.

In any case, hopefully this library will now successfully hide that detail of the underlying C++ and deliver to its users a bit better of an experience than (though, strictly speaking, by being slightly incompatible with) the underlying C++ code.
