### ISSUE TITLE
Alpha-5 format export not behaving as I would naively expect ;)

### ISSUE THREAD

**Issue by ckuethe** [brandon-rhodes/python-sgp4#97]
Short version, if `Satellite.satnum` is greater than 99999, TLEs with no object number are produced. Here's a demonstration script; I was expecting that if _satnum is an integer greater than 99999_, the exporter would correctly encode it as alpha-5.

```
#!/usr/bin/env python3

from scipy.stats.contingency import expected_freq
from sgp4.io import twoline2rv
from sgp4 import exporter
from sgp4.earth_gravity import wgs72

# from https://celestrak.com/NORAD/elements/stations.txt
original_tle = (
    "1 25544U 98067A   21245.66660925  .00003909  00000-0  80185-4 0  9991",
    "2 25544  51.6444 319.5951 0003037 346.9445 145.3381 15.48588378300608",
)

# can I round-trip the TLE successfully?
iss_one = twoline2rv(original_tle[0], original_tle[1], wgs72)
iss_one_tle = exporter.export_tle(iss_one)
assert iss_one_tle == original_tle

# Unnecessary paranoia
iss_two = twoline2rv(iss_one_tle[0], iss_one_tle[1], wgs72)
assert iss_one.intldesg == iss_two.intldesg
assert iss_one.ecco == iss_two.ecco
assert iss_one.a == iss_two.a

# Can I increment the satnum?
bump_satnum = 12345
iss_two.satnum += bump_satnum
modified_tle = exporter.export_tle(iss_two)
modified_obj = twoline2rv(modified_tle[0], modified_tle[1], wgs72)
assert modified_obj.satnum - iss_one.satnum == bump_satnum

# Can I export this new alpha-5 format?
a5 = "A1234"
iss_two.satnum = a5
modified_tle = exporter.export_tle(iss_two)
assert a5 in modified_tle[0] and a5 in modified_tle[1]

# what happens if I try to load it
modified_obj = twoline2rv(modified_tle[0], modified_tle[1], wgs72)
final_tle = exporter.export_tle(modified_obj)
if iss_two.satnum != modified_obj.satnum:
    print(f"round trip fail: {modified_obj.satnum} != {iss_two.satnum}")
if modified_tle != final_tle:
    print(f"A5 test fail\n\texpected:{modified_tle}\n\tcomputed:{final_tle}")
```

```
$ python iss.py 
101234
round trip fail: 101234 != A1234
A5 test fail
	expected:('1 A1234U 98067A   21245.66660925  .00003909  00000-0  80185-4 0  9991', '2 A1234  51.6444 319.5951 0003037 346.9445 145.3381 15.48588378300608')
	computed:('1 U 98067A   21245.66660925  .00003909  00000-0  80185-4 0  9991', '2  51.6444 319.5951 0003037 346.9445 145.3381 15.48588378300608')
```

I'm using python-sgp4 2,20 on xubuntu 21.04 x86_64

**Comment by brandon-rhodes** [comment]
I'm not sure that the new export routine is designed to work with the old `Satellite` object that's returned from the deprecated `twoline2rv()` function.

Could you try over again, but with `from sgp4.api import Satrec` and `Satrec.twoline2rv()` instead?

It will probably still give an error, but at least we'll be comparing modern code instead of the tangle of legacy code. Thanks!

**Comment by ckuethe** [comment]
Sure. Using the new API methods I get an error when attempting to modify the Satellite number

```
$ python iss.py 
Traceback (most recent call last):
  File "/home/ckuethe/satobs-tools/iss.py", line 25, in <module>
    iss_two.satnum += bump_satnum
AttributeError: attribute 'satnum' of 'sgp4.vallado_cpp.Satrec' objects is not writable
```

Here's the new version

```
#!/usr/bin/env python3

from sgp4.api import Satrec, WGS72
from sgp4 import exporter

# from https://celestrak.com/NORAD/elements/stations.txt
original_tle = (
    "1 25544U 98067A   21245.66660925  .00003909  00000-0  80185-4 0  9991",
    "2 25544  51.6444 319.5951 0003037 346.9445 145.3381 15.48588378300608",
)

# can I round-trip the TLE successfully?
iss_one = Satrec.twoline2rv(original_tle[0], original_tle[1], WGS72)
iss_one_tle = exporter.export_tle(iss_one)
assert iss_one_tle == original_tle

# Unnecessary paranoia
iss_two = Satrec.twoline2rv(iss_one_tle[0], iss_one_tle[1], WGS72)
assert iss_one.intldesg == iss_two.intldesg
assert iss_one.ecco == iss_two.ecco
assert iss_one.a == iss_two.a

# Can I increment the satnum?
bump_satnum = 12345
iss_two.satnum += bump_satnum
modified_tle = exporter.export_tle(iss_two)
modified_obj = Satrec.twoline2rv(modified_tle[0], modified_tle[1], WGS72)
assert modified_obj.satnum - iss_one.satnum == bump_satnum

# Can I export this new alpha-5 format?
a5 = "A1234"
iss_two.satnum = a5
modified_tle = exporter.export_tle(iss_two)
assert a5 in modified_tle[0] and a5 in modified_tle[1]

# what happens if I try to load it
modified_obj = Satrec.twoline2rv(modified_tle[0], modified_tle[1], WGS72)
final_tle = exporter.export_tle(modified_obj)
if iss_two.satnum != modified_obj.satnum:
    print(f"round trip fail: {modified_obj.satnum} != {iss_two.satnum}")
if modified_tle != final_tle:
    print(f"A5 test fail\n\texpected:{modified_tle}\n\tcomputed:{final_tle}")
```

**Comment by brandon-rhodes** [comment]
> Sure. Using the new API methods I get an error when attempting to modify the Satellite number

Excellent! Thanks for upgrading to the objects that more tightly follow how the real SGP4 record behaves.

The method available at the moment for updating satellite fields is the `sgp4init()` method:

https://pypi.org/project/sgp4/#providing-your-own-elements

Are you in a situation where you need to adjust only the number, and so calling `sgp4init()` will be a burden? If so, then we could think about adding a setter for that attribute, as a project for a volunteer or else for me if I get time.

**Comment by ckuethe** [comment]
If you're amenable to having a setter, then I'm amenable to doing up a PR.

I have use cases where I might want to change the satellite number, and use cases where I do have to construct a whole satellite record from orbital elements. In this case I was exploring Alpha-5 and adding 100000 to an otherwise valid TLE seemed like the fastest way to see what would happen.

**Comment by ckuethe** [comment]
@brandon-rhodes any thoughts on #98 ?

**Comment by brandon-rhodes** [comment]
Not yet — given my schedule, it might not be til late October that I'm able to sit down for a code review? We'll see!

**Comment by brandon-rhodes** [comment]
After several months of weighing the matter, I realized why this was making the code so complex: because we were insisting on continuing to hide the fact that `satnum` is now a string in the official `struct elsetrec`, which meant having to build ever more elaborate versions of the fiction that it's an integer.

So I have taken another approach:

There's now a readable and writeable `satnum_str` attribute. It's simple to implement and reason about, because it simply exposes the underlying string from the C++ code.

Then, I've switched `satnum` — which was never writeable anyway, as you note above — to being a property that, if the user looks at it for legacy reasons (hopefully users will just be happy with `satnum_str`), does the alpha-5 decoding to try to create an integer.

Which means that `io.py` and `exporter.py` become blissfully unaware of alpha-5 at all, because they can simply read in the string and write out the string without any conversions whatsoever!

So, I think this means that you get what you wanted — a way to write the satnum on-the-fly into an already-existing satellite object — but with the code becoming simpler overall rather than more complicated. Hopefully a new release will come soon so you can try it out!

**Comment by ckuethe** [comment]
Cool. This does now give me a way to set arbitrary satellite numbers.

I just needed to dash together a little int <--> alpha5 converter so that I can refer to `314159` or `X4159` and sort them in a database.

**Comment by brandon-rhodes** [comment]
> I just needed to dash together a little int <--> alpha5 converter so that I can refer to `314159` or `X4159` and sort them in a database.

The `sgp4.alpha5` module has conversion functions you can use. Maybe I should document them for the next version of sgp4.
